name: Alerta Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ejecutar el Hola Mundo en Python
      - name: Run Hola Mundo
        run: javascript6 script.js

      # 3. Enviar notificación enriquecida a ntfy.sh
      - name: Send notification to ntfy.sh
        run: |
          curl -H "Title: CI/CD - Electiva 2 DevOps" \
               -H "Priority: high" \
               -H "Tags: github,ci,devops,itla" \
               -d $'Build EXITOSO ✅\n\nEstudiante: Esmerlyn Ledesma #2022-1775 \nCurso: Electiva 2 - DevOps\nProfesor: Elys Cruz\n\nRepositorio: https://github.com/ledesma09/Electiva2Inte.git \nRama: main \n\nVer detalles: https://github.com/ledesma09/Electiva2Inte.git' \
               ntfy.sh/devops-itla
